# Generated by Django 4.2.7 on 2023-11-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('designation', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
